
package com.example.apache.cxf.calc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operations", targetNamespace = "http://calc.cxf.apache.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operations {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.AddResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "div", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.DivResponse")
    public int div(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sub", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.SubResponse")
    public int sub(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOutput", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.GetOutput")
    @ResponseWrapper(localName = "getOutputResponse", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.GetOutputResponse")
    public String getOutput();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multi", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.Multi")
    @ResponseWrapper(localName = "multiResponse", targetNamespace = "http://calc.cxf.apache.example.com/", className = "com.example.apache.cxf.calc.MultiResponse")
    public int multi(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
